[package]
name = "cell_automata"
version = "0.1.0"
authors = ["dsilin","brundolf"]
edition = "2018"

[dependencies]
piston_window = "0.132.0"
clap = "4.5.9"
crossbeam = "0.8.4"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
