[package]
name = "entropylife"
version = "0.1.0"
authors = ["dsilin","brundolf"]
edition = "2018"

[dependencies]
piston_window = "0.107.0"
rand = "0.6.5"
crossbeam = "0.7.3"

[profile.dev]
opt-level = 3
